"""
Stage 5: generate every result-bearing table body for the manuscript from results/*.csv.

Outputs  tables/tab_recovery_body.tex      Table tab:recovery      (results/table5_recovery.csv)
         tables/tab_ident_body.tex         Table tab:ident         (structural.csv, spec_comparison.csv)
         tables/tab_placebo_body.tex       Table tab:placebo       (placebo_detail.csv)
         tables/tab_placebodetail_body.tex Table tab:placebodetail (placebo_detail.csv)
         tables/tab_activity_body.tex      Table tab:activity      (spec_comparison.csv)
         tables/tab_welfare_body.tex       Table tab:welfare       (structural.csv)
         tables/tab_excess_body.tex        Table tab:excess        (table3_excess_clean.csv)
         tables/tab_alphasens_body.tex     Table tab:alphasens     (alpha_sweep.csv)
         tables/tab_intensity_body.tex     Table tab:intensity     (data/pgcb_V1_raw.csv)
         tables/tab_depth_body.tex         Table tab:depth         (results/hourly_clean.csv, panel_daily.csv)
         tables/numbers.tex                \\newcommand macros for in-text figures
main.tex \\input{}s these files; nothing numerical in those tables is typed by hand.
"""
import os
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results"); TAB = os.path.join(HERE, "tables")
os.makedirs(TAB, exist_ok=True)
MAIN = "none"                       # main specification (Section 6.5)
SPECS = ["none", "+growth", "+level"]
LABEL = {"none": r"\textbf{none}", "+growth": r"$+$growth", "+level": r"$+$level"}
# modelled cost-revenue gap (m USD at 122 BDT/USD): regenerated by cost_model.py (stage 9) from
# data/table1_params.csv, data/tariff_series.csv and the hourly source mix -> results/cost_model.csv.
# Mixed-price calculation: FY2025 per-unit costs against each year's nominal average tariff.
def load_gap():
    cm = pd.read_csv(os.path.join(RES, "cost_model.csv")).set_index("year")
    if "gap_mUSD_at_122" not in cm.columns:
        raise SystemExit("results/cost_model.csv has no gap column: supply data/tariff_series.csv and run cost_model.py")
    return {int(y): float(v) for y, v in cm["gap_mUSD_at_122"].items()}, cm


def sp(v): return f"${v:+.2f}$"
def w(name, body): open(os.path.join(TAB, name), "w", encoding="utf-8").write(body + "\n")
def sci(x):
    e = int(np.floor(np.log10(x))); m = round(x / 10**e, 1)
    if m >= 10.0: m, e = 1.0, e + 1
    return f"${m:.1f}\\times10^{{{e}}}$"




# ---------------------------------------------------------------- Section 4 / 5 quantities
def regime_tables(N):
    """tab:intensity, tab:depth and the Section 4-5 macros, from data/pgcb_V1_raw.csv and
    results/hourly_clean.csv / panel_daily.csv. Peak hours are labels 18-21."""
    DATA = os.path.join(HERE, "data")
    raw = pd.read_csv(os.path.join(DATA, "pgcb_V1_raw.csv")); raw["dt"] = pd.to_datetime(raw.datetime)
    raw["yr"] = raw.dt.dt.year; raw["hr"] = raw.dt.dt.hour; raw["res"] = raw.demand_mw - raw.generation_mw - raw.load_shedding
    H = pd.read_csv(os.path.join(RES, "hourly_clean.csv"), index_col="dt", parse_dates=True).dropna()
    P = pd.read_csv(os.path.join(RES, "panel_daily.csv"), index_col="date", parse_dates=True)
    PEAK = [18, 19, 20, 21]
    cri = raw[raw.yr.between(2022, 2024)]
    # --- tab:intensity (raw record, :30 rows retained)
    rows = []
    for h in (1, 4, 7, 10, 13, 16, 19, 22):
        g = cri[cri.hr == h]; lab = f"{h:02d} \\textsc{{(peak)}}" if h in PEAK else f"{h:02d}"
        rows.append(f"{lab} & {100*(g.load_shedding>0).mean():.1f} & {g.load_shedding.mean():.1f} & {g.load_shedding[g.load_shedding>0].mean():.1f} \\\\")
    p, o = cri[cri.hr.isin(PEAK)], cri[~cri.hr.isin(PEAK)]
    pp, po = (p.load_shedding > 0).mean(), (o.load_shedding > 0).mean()
    ep, eo = p.load_shedding.mean(), o.load_shedding.mean()
    cp, co = p.load_shedding[p.load_shedding > 0].mean(), o.load_shedding[o.load_shedding > 0].mean()
    rows += [r"\midrule", f"Peak (18--21)  & {100*pp:.1f} & {ep:.1f} & {cp:.1f} \\\\", f"Off peak       & {100*po:.1f} & {eo:.1f} & {co:.1f} \\\\",
             f"\\textbf{{Ratio}} & \\textbf{{{pp/po:.3f}}} & \\textbf{{{ep/eo:.3f}}} & \\textbf{{{cp/co:.3f}}} \\\\"]
    w("tab_intensity_body.tex", "\n".join(rows))
    hh = cri.groupby("hr").load_shedding.mean()
    N.update({"IntOccRatio": f"{pp/po:.3f}", "IntPeakMW": f"{ep:.0f}", "IntOffMW": f"{eo:.0f}", "IntRatio": f"{ep/eo:.3f}", "IntCondRatio": f"{cp/co:.3f}",
              "IntMaxMW": f"{hh.max():.0f}", "IntMaxHour": f"{int(hh.idxmax()):02d}:00"})
    g25 = raw[raw.yr == 2025]; p25, o25 = g25[g25.hr.isin(PEAK)], g25[~g25.hr.isin(PEAK)]
    N.update({"OccTwentyFive": f"{(p25.load_shedding>0).mean()/(o25.load_shedding>0).mean():.3f}", "IntTwentyFive": f"{p25.load_shedding.mean()/o25.load_shedding.mean():.3f}"})
    # --- PCR by year (cleaned hourly record), hourly probability range, p99/p90
    Hc = H.copy(); Hc["hr"] = Hc.index.hour; Hc["yr"] = Hc.index.year
    for y, nm in [(2022, "Two"), (2023, "Three"), (2024, "Four"), (2025, "Five")]:
        g = Hc[Hc.yr == y]; a = (g[g.hr.isin(PEAK)].load_shedding > 0).mean() / (g[~g.hr.isin(PEAK)].load_shedding > 0).mean()
        N[f"PcrTwenty{nm}"] = f"{a:.2f}"
    ph = (cri.load_shedding > 0).groupby(cri.hr).mean() * 100
    N.update({"HourPLo": f"{ph.min():.0f}", "HourPHi": f"{ph.max():.0f}"})
    for y, nm in [(2021, "TwentyOne"), (2023, "TwentyThree")]:
        g = H[H.index.year == y].generation_mw; N[f"TailRatio{nm}"] = f"{g.quantile(.99)/g.quantile(.90):.3f}"
    # --- SDI (raw record; peak = maximum hourly generation on the cleaned record)
    peak = H.generation_mw.max()
    N.update({"SdiExact": f"{100*(cri.res==0).mean():.1f}", "SdiTwoTenths": f"{100*(cri.res.abs()<=0.002*peak).mean():.1f}",
              "SdiHalfLo": f"{min(100*(raw[raw.yr==y].res.abs()<=0.005*peak).mean() for y in (2022,2023,2024)):.0f}",
              "SdiHalfHi": f"{max(100*(raw[raw.yr==y].res.abs()<=0.005*peak).mean() for y in (2022,2023,2024)):.0f}",
              "SystemPeakMW": f"{peak:,.0f}".replace(",", "{,}")})
    # --- tab:depth (cleaned record)
    rows = []; dep = {}
    for y in (2022, 2023, 2024, 2025):
        d_ = P[P.index.year == y]; h_ = H[H.index.year == y]
        hpd = (h_.load_shedding > 0).groupby(h_.index.normalize()).sum(); hpd = hpd[hpd > 0].mean()
        dmx = h_.load_shedding.groupby(h_.index.normalize()).max(); dmx = dmx[dmx > 0].mean()
        mwh = d_.S[d_.S > 0].mean(); ds = 100 * (d_.S > 0).mean(); sg = 100 * d_.S.sum() / d_.G.sum()
        dep[y] = (ds, hpd, dmx, mwh, sg)
        rows.append(f"{y} & {ds:.1f} & {hpd:.1f} & {dmx:.0f} & {mwh:.0f} & {sg:.2f} \\\\")
    w("tab_depth_body.tex", "\n".join(rows))
    for y, nm in [(2022, "Two"), (2023, "Three"), (2024, "Four"), (2025, "Five")]:
        N[f"DaysShedTwenty{nm}"] = f"{dep[y][0]:.1f}"
    N.update({"HrsTwentyThree": f"{dep[2023][1]:.1f}", "HrsTwentyFive": f"{dep[2025][1]:.1f}", "HrsDeclinePct": f"{100*(1-dep[2025][1]/dep[2023][1]):.0f}",
              "MaxTwentyThree": f"{dep[2023][2]:.0f}", "MaxTwentyFive": f"{dep[2025][2]:.0f}", "MaxDeclinePct": f"{100*(1-dep[2025][2]/dep[2023][2]):.0f}",
              "MwhTwentyThree": f"{dep[2023][3]:.0f}", "MwhTwentyFive": f"{dep[2025][3]:.0f}", "MwhDeclinePct": f"{100*(1-dep[2025][3]/dep[2023][3]):.0f}"})
    return N


def main():
    rec = pd.read_csv(os.path.join(RES, "table5_recovery.csv"))
    W = pd.read_csv(os.path.join(RES, "structural.csv"))
    C = pd.read_csv(os.path.join(RES, "spec_comparison.csv")).set_index("spec")
    PL = pd.read_csv(os.path.join(RES, "placebo_detail.csv"))
    T3 = pd.read_csv(os.path.join(RES, "table3_excess_clean.csv"))
    A = pd.read_csv(os.path.join(RES, "alpha_sweep.csv"))
    years = [2022, 2023, 2024, 2025]
    Wm = W[W.spec == MAIN].set_index("year")

    # --- tab:recovery
    rows = [f"{int(r.holdout)} ({int(r.n_train):,}) & {int(r.admitted):>3d} & {sp(r.true_supp)} & {sp(r.tobit)} & {sp(r.icg)} \\\\" for _, r in rec.iterrows()]
    mae_t = (rec.tobit - rec.true_supp).abs().mean(); mae_i = (rec.icg - rec.true_supp).abs().mean()
    w("tab_recovery_body.tex", "\n".join(rows) + "\n\\midrule\n" + r"\multicolumn{3}{l}{Mean abs.\ calibration error} & " + f"{mae_t:.2f} & {mae_i:.2f}" + r" \\")

    # --- tab:ident
    rows = []
    for y in years:
        cells = []
        for s in SPECS:
            r = W[(W.spec == s) & (W.year == y)].iloc[0]
            cells.append((r"\textbf{" + sp(r.gap_pp) + "}") if r.inside_bound else sp(r.gap_pp))
        rows.append(f"{y} & {Wm.loc[y,'bound_lower_pp']:.2f} & {Wm.loc[y,'bound_upper_pp']:.2f} & " + " & ".join(cells) + r" \\")
    tail = [r"\multicolumn{3}{l}{In-sample sd of annual gap, 2016--2021 (pp)} & " + " & ".join(f"{C.loc[s,'insample_annual_gap_sd']:.2f}" for s in SPECS) + r" \\",
            r"\multicolumn{3}{l}{Rolling-origin RMSE, normal targets, $n=3$ (pp)} & " + " & ".join(f"{C.loc[s,'oos_rmse_normal']:.2f}" for s in SPECS) + r" \\",
            r"\multicolumn{3}{l}{Rolling-origin RMSE, across COVID break, $n=6$ (pp)} & " + " & ".join(f"{C.loc[s,'oos_rmse_covid']:.2f}" for s in SPECS) + r" \\",
            r"\multicolumn{3}{l}{Rolling-origin RMSE, pooled, $n=9$ (pp)} & " + " & ".join(f"{C.loc[s,'oos_rmse_pooled']:.2f}" for s in SPECS) + r" \\",
            r"\multicolumn{3}{l}{Design condition number} & " + " & ".join(sci(C.loc[s, "cond"]) for s in SPECS) + r" \\"]
    w("tab_ident_body.tex", "\n".join(rows) + "\n\\midrule\n" + "\n".join(tail))

    # --- tab:placebo (main spec)
    pm = PL[PL.spec == MAIN]
    def strat(m, lab):
        g = pm[m].gap_pp; return f"{lab} & {len(g)} & {sp(g.mean())} & " + (r"\textbf{" + f"{np.sqrt((g**2).mean()):.2f}" + "}" if lab[0] != "P" else f"{np.sqrt((g**2).mean()):.2f}") + f" & {g.abs().max():.2f} \\\\"
    w("tab_placebo_body.tex", "\n".join([strat(pm.stratum == "normal", "Normal years (2018, 2019)        "),
                                          strat(pm.stratum == "covid_break", "Across the COVID break (2020--21)"),
                                          r"\midrule", strat(pm.stratum.notna(), "Pooled                           ")]))

    # --- tab:placebodetail
    pv = PL.pivot(index=["origin", "n_train", "h", "target", "S_over_G_pct"], columns="spec", values="gap_pp").reset_index()
    rows = [f"{int(r.origin)} & {int(r.n_train):,} & {int(r.h)} & {int(r.target)} & {r.S_over_G_pct:.3f} & {sp(r['none'])} & {sp(r['+growth'])} & {sp(r['+level'])} \\\\" for _, r in pv.iterrows()]
    w("tab_placebodetail_body.tex", "\n".join(rows))

    # --- tab:activity
    best = {c: C[c].idxmin() for c in ["insample_annual_gap_sd", "oos_rmse_pooled", "oos_rmse_normal"]}
    rows = []
    for s in SPECS:
        g = [W[(W.spec == s) & (W.year == y)].gap_pp.iloc[0] for y in (2022, 2023, 2024)]
        def b(col): v = f"{C.loc[s,col]:.2f}"; return r"\textbf{" + v + "}" if best[col] == s else v
        rows.append(f"{LABEL[s]} & {sp(g[0])} & {sp(g[1])} & {sp(g[2])} & {b('insample_annual_gap_sd')} & {b('oos_rmse_pooled')} & {b('oos_rmse_normal')} & {sci(C.loc[s,'cond'])} \\\\")
    w("tab_activity_body.tex", "\n".join(rows))

    # --- tab:welfare (modelled gap column from cost_model.py)
    MODELLED_GAP, CM = load_gap()
    rows = []
    for y in years:
        r = Wm.loc[y]
        st = f"{r.unserved_TWh:.2f}" if r.inside_bound else r"\itshape " + f"{r.unserved_TWh:.2f}"
        rows.append(f"{y} & {r.bound_lower_TWh:.2f} & {r.bound_upper_TWh:.2f} & {st} & {r.bound_lower_mUSD_voll90:.0f} & {r.bound_upper_mUSD_voll90:.0f} & {MODELLED_GAP[y]:.0f} \\\\")
    w("tab_welfare_body.tex", "\n".join(rows))
    EXTRA = {}
    # macros for the gap, the break-even value of lost load (gap / interval width) and the real tariff change
    for y, nm in [(2022, "TwentyTwo"), (2023, "TwentyThree"), (2024, "TwentyFour"), (2025, "TwentyFive")]:
        width_twh = Wm.loc[y, "bound_upper_TWh"] - Wm.loc[y, "bound_lower_TWh"]
        EXTRA[f"GapUsd{nm}"] = f"{MODELLED_GAP[y]:.0f}"
        EXTRA[f"GapBnUsd{nm}"] = f"{MODELLED_GAP[y]/1000:.1f}"
        EXTRA[f"BreakEven{nm}"] = f"{CM.loc[y, 'gap_bn_BDT'] / width_twh:.0f}"     # bn BDT / TWh = BDT/kWh
    EXTRA["SpreadBnUsdTwentyThree"] = f"{(Wm.loc[2023,'bound_upper_mUSD_voll90'] - Wm.loc[2023,'bound_lower_mUSD_voll90'])/1000:.1f}"
    import json
    S = json.load(open(os.path.join(HERE, "data", "wdi_conversion_series.json")))
    cpi_b = {int(k): v for k, v in S["cpi_bgd"].items()}
    t21, t25 = CM.loc[2021, "tariff_bdt_kwh"], CM.loc[2025, "tariff_bdt_kwh"]
    real = (t25 / t21) / (cpi_b[2025] / cpi_b[2021]) - 1
    EXTRA.update({"TariffTwentyOne": f"{t21:.2f}", "TariffTwentyFive": f"{t25:.2f}", "RealTariffChangePct": f"{-100*real:.1f}",
              "ElastLo": f"{-100*real*0.1:.1f}", "ElastHi": f"{-100*real*0.3:.1f}",
              "TariffLo": f"{CM.tariff_bdt_kwh.min():.2f}", "TariffHi": f"{CM.tariff_bdt_kwh.max():.2f}"})

    # --- tab:excess
    w("tab_excess_body.tex", "\n".join(f"{int(r.year)} & {r.hours_with_excess_pct:.1f} & {r.median_excess_MW:.0f} & {r.excess_pct_of_generation:.2f} \\\\" for _, r in T3.iterrows()))

    # --- tab:alphasens
    rows = [f"{r.alpha_min:.2f} & " + " & ".join(f"{r[f'upper_pp_{y}']:5.2f}" for y in years) + r" \\" for _, r in A.iterrows()]
    rows.append(r"\midrule"); rows.append(r"Lower limit (all $\alpha_{\min}$) & " + " & ".join(f"{A.iloc[0][f'lower_pp_{y}']:.2f}" for y in years) + r" \\")
    w("tab_alphasens_body.tex", "\n".join(rows))

    # --- numbers.tex : in-text macros (all from the same result files)
    a23 = A.set_index("alpha_min")
    lvl = W[W.spec == "+level"].set_index("year")
    # interval-width diagnostics for Appendix A (censored days of the estimation panel, alpha_min = 0.30)
    _P = pd.read_csv(os.path.join(RES, "panel_daily.csv"))
    _c = _P[(_P.shed.astype(str) == "True") | (_P.shed == 1)]; _c = _c[_c.S > 0]
    _w = np.log(_c.G + _c.S / 0.30) - np.log(_c.G + _c.S)
    narrow4, narrow3 = (_w < 1e-4).sum(), (_w < 1e-3).sum()
    N = {
        "MainGapTwentyThree": f"{Wm.loc[2023,'gap_pp']:.2f}", "MainGapTwentyFour": f"{Wm.loc[2024,'gap_pp']:.2f}",
        "MainGapTwentyFive": f"{Wm.loc[2025,'gap_pp']:.2f}", "MainGapTwentyTwo": f"{Wm.loc[2022,'gap_pp']:.2f}",
        "MainTwhTwentyThree": f"{Wm.loc[2023,'unserved_TWh']:.2f}", "MainTwhTwentyFour": f"{Wm.loc[2024,'unserved_TWh']:.2f}",
        "MainUsdTwentyThree": f"{Wm.loc[2023,'cost_mUSD_voll90']:.0f}", "MainUsdTwentyFour": f"{Wm.loc[2024,'cost_mUSD_voll90']:.0f}",
        "BootLoTwentyThree": f"{Wm.loc[2023,'boot_p05']:.2f}", "BootHiTwentyThree": f"{Wm.loc[2023,'boot_p95']:.2f}",
        "BootLoUsdTwentyThree": f"{Wm.loc[2023,'boot_p05_mUSD_voll90']:.0f}", "BootHiUsdTwentyThree": f"{Wm.loc[2023,'boot_p95_mUSD_voll90']:.0f}",
        "BootLoTwentyFive": f"{Wm.loc[2025,'boot_p05']:.2f}", "BootHiTwentyFive": f"{Wm.loc[2025,'boot_p95']:.2f}",
        "BoundLoTwentyThree": f"{Wm.loc[2023,'bound_lower_pp']:.2f}", "BoundHiTwentyThree": f"{Wm.loc[2023,'bound_upper_pp']:.2f}",
        "BoundLoTwhTwentyThree": f"{Wm.loc[2023,'bound_lower_TWh']:.2f}", "BoundHiTwhTwentyThree": f"{Wm.loc[2023,'bound_upper_TWh']:.2f}",
        "BoundLoUsdTwentyThree": f"{Wm.loc[2023,'bound_lower_mUSD_voll90']:.0f}", "BoundHiUsdTwentyThree": f"{Wm.loc[2023,'bound_upper_mUSD_voll90']:.0f}",
        "RmseNormal": f"{C.loc[MAIN,'oos_rmse_normal']:.2f}", "RmseCovid": f"{C.loc[MAIN,'oos_rmse_covid']:.2f}",
        "RmsePooled": f"{C.loc[MAIN,'oos_rmse_pooled']:.2f}", "MaxSpurious": f"{C.loc[MAIN,'oos_max_pooled']:.2f}",
        "InSampleSd": f"{C.loc[MAIN,'insample_annual_gap_sd']:.2f}", "TrendPct": f"{C.loc[MAIN,'trend_pct_yr']:.1f}",
        "RsqDaily": f"{C.loc[MAIN,'R2']:.2f}", "NTrain": f"{int(C.loc[MAIN,'n_train']):,}".replace(",", "{,}"),
        "LevelTrendPct": f"{C.loc['+level','trend_pct_yr']:.1f}", "LevelGapTwentyFive": f"{lvl.loc[2025,'gap_pp']:.2f}",
        "LevelBootLoTwentyFive": f"{lvl.loc[2025,'boot_p05']:.2f}", "LevelBootHiTwentyFive": f"{lvl.loc[2025,'boot_p95']:.2f}",
        # reported-scenario range = none and +level only; +growth is the cautionary case and is quoted separately
        "GapRangeLoTwentyThree": f"{W[(W.year==2023)&(W.spec!='+growth')].gap_pp.min():.2f}", "GapRangeHiTwentyThree": f"{W[(W.year==2023)&(W.spec!='+growth')].gap_pp.max():.2f}",
        "UsdRangeLoTwentyThree": f"{W[(W.year==2023)&(W.spec!='+growth')].cost_mUSD_voll90.min():.0f}", "UsdRangeHiTwentyThree": f"{W[(W.year==2023)&(W.spec!='+growth')].cost_mUSD_voll90.max():.0f}",
        "UsdRangeLoBnTwentyThree": f"{W[(W.year==2023)&(W.spec!='+growth')].cost_mUSD_voll90.min()/1000:.1f}", "UsdRangeHiBnTwentyThree": f"{W[(W.year==2023)&(W.spec!='+growth')].cost_mUSD_voll90.max()/1000:.1f}",
        "GrowthGapTwentyThree": f"{W[(W.year==2023)&(W.spec=='+growth')].gap_pp.iloc[0]:.2f}", "GrowthUsdTwentyThree": f"{W[(W.year==2023)&(W.spec=='+growth')].cost_mUSD_voll90.iloc[0]:.0f}",
        "GrowthUsdBnTwentyThree": f"{W[(W.year==2023)&(W.spec=='+growth')].cost_mUSD_voll90.iloc[0]/1000:.1f}",
        "NCensored": f"{len(_c):,}".replace(",", "{,}"), "NDays": f"{len(_P):,}".replace(",", "{,}"),
        "NarrowTenFour": f"{int(narrow4)}", "NarrowTenThree": f"{int(narrow3)}",
        "MaeTobit": f"{mae_t:.2f}", "MaeIcg": f"{mae_i:.2f}",
        "AlphaContain": f"{Wm.loc[2023,'bound_lower_pp']/Wm.loc[2023,'gap_pp']:.2f}",
        "AlphaUsdLo": f"{a23.loc[0.30,'lower_mUSD_2023']:.0f}", "AlphaUsdTwo": f"{a23.loc[0.20,'upper_mUSD_2023']:.0f}",
        "AlphaUsdThree": f"{a23.loc[0.30,'upper_mUSD_2023']:.0f}", "AlphaUsdFive": f"{a23.loc[0.50,'upper_mUSD_2023']:.0f}",
        "AlphaUsdSeven": f"{a23.loc[0.70,'upper_mUSD_2023']:.0f}", "AlphaPpFive": f"{a23.loc[0.50,'upper_pp_2023']:.2f}",
        "ExcessGwh": f"{T3[T3.year<=2024].excess_GWh.sum():.1f}",
    }
    N = regime_tables(N)
    N.update(EXTRA)
    # Tobit penalty sweep (tobit_penalty_sweep.py) and the 2024 upper bound in TWh, so Section 6.1 and Appendix A quote one file
    sw = pd.read_csv(os.path.join(RES, "tobit_penalty_sweep.csv")).set_index("lambda")
    N.update({"SweepPointOne": f"{sw.loc[0.1,'tobit_correction_pp']:+.1f}", "SweepOne": f"{sw.loc[1.0,'tobit_correction_pp']:+.1f}",
              "SweepTen": f"{sw.loc[10.0,'tobit_correction_pp']:+.1f}", "SweepHundred": f"{sw.loc[100.0,'tobit_correction_pp']:+.1f}",
              "SweepTruth": f"{sw.true_supp_pp.iloc[0]:.1f}",
              "BoundHiTwhTwentyFour": f"{Wm.loc[2024,'bound_upper_TWh']:.2f}"})
    w("numbers.tex", "\n".join(f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in N.items()))
    print(f"wrote {len(os.listdir(TAB))} files to tables/")


if __name__ == "__main__":
    main()
